INSERT INTO USER(USERNAME, PASSWORD)VALUES('user123', 'user123');

insert into PRODUCT (SKU_NUMBER, SKU_NAME)VALUES('test2', '測試商品2');

INSERT INTO PERSON(NAME, SEX, AGE)VALUES('測試男','男',20);
INSERT INTO PERSON(NAME, SEX, AGE)VALUES('測試女','女',30);

