DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PERSON;


CREATE TABLE PRODUCT(
	PRODUCT_ID int NOT NULL AUTO_INCREMENT,
	SKU_NUMBER VARCHAR(50) NOT null unique,
	SKU_NAME VARCHAR(50) NOT null,
	primary KEY(PRODUCT_ID)
);

CREATE TABLE PERSON(
	ID int NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(50),
	SEX VARCHAR(10),
	AGE int	
);